### PR TITLE
Fixes 'warning: ::Fixnum is deprecated' for ruby 2.4+

### PR DESCRIPTION
**Pull request by grzuy**
Fixes warning `warning: constant ::Fixnum is deprecated` for ruby 2.4+`

### CODE REVIEW

**Comment by cabo** [comment]
Hi, thank you for looking into this.  Are you seeing some actual warnings or is this just a precautionary change?   Unfortunately, the CI scripts for Ruby 2.0..2.2 broke; have you tested your change with this version?

**Comment by grzuy** [comment]
Yes, there's an actual warning when I run tests with `$ bundle exec rspec` in `master`.

Tests were green and warning gone for me sitting in this new branch for rubies:

* `2.0.0-p648`
* `2.1.10`
* `2.2.10`
* `2.2.2`
* `2.3.7`
* `2.4.4`
* `2.5.1` and
* `2.6.0-preview2`

using `ruby-install` and `chruby`.

**Comment by PJK** [comment]
Thank you very much for the PR, @grzuy! Please merge master, I have fixed #2, which should fix the CI issue.

I am not sure the older rubies will still work, but we should kill everything [older than 2.3](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/) anyway (#4).

**Comment by grzuy** [comment]
Hi @PJK, thank you for fixing CI builds!

PR updated with latest `master`.

**Comment by PJK** [comment]
In it goes, thank you!

**Pull request merged**
